version: "3"
services: 
  app: 
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: app
    image: app
    ports: 
      - "3000:3000"
    environment:
      - SHIP_API_URL
      - APP_BASE_URL
      - VERBOSE_LOGGING
      - SEGMENT_WRITE_KEY
      - POLL_INTERVAL
    restart: always
